version: '3'
services:
#   nginx:
#     image: nginx:latest
#     ports:
#       - 80:80
#     restart: always  
#     volumes:
#       - ./nginx/conf.d:/etc/nginx/conf.d
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - /tmp/logs:/var/log/nginx

    redis-server:
        image: redis:latest
        ports:
        - 6479:6379
        restart: always
        container_name: redis-server

    app:
        build: ./
        volumes:
        - ./:/usr/local/app
        restart: always  
        working_dir: /usr/local/app
        command: npm start
        container_name: app
        depends_on:
        - redis-server
        - mysql
        links:
        - redis-server:rd
        - mysql:md
    mysql:
        image: mysql:5.7.22
        ports:
            - 3307:3307
        restart: always
        container_name: mysql
        # volumes:
        #     - /usr/local/mysql:/var/lib/mysql
        environment:
            # - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=123456
        