version: '3'
services:
#   nginx:
#     image: nginx:latest
#     ports:
#       - 80:80
#     restart: always  
#     volumes:
#       - ./nginx/conf.d:/etc/nginx/conf.d
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - /tmp/logs:/var/log/nginx

    redis-server:
        image: redis:latest
        ports:
        - 6379:6379
        restart: always
        container_name: redis-server
        networks:
            - "net1"
        expose:
            - 80

    app:
        build: ./
        volumes:
        - ./:/usr/local/app
        restart: always  
        working_dir: /usr/local/app
        command: npm start
        container_name: app
        depends_on:
        - redis-server
        - mysql
        links:
        - redis-server:rd
        - mysql:md
        ports:
        - 8080:8080
        networks:
            - "net1"
            - "net2"
        expose:
            - 80
    mysql:
        image: mysql:5.7.22
        ports:
        - 3307:3306
        logging:
            driver: "json-file"
            options:
                max-size: "1000k"
                max-file: "40"
        restart: always
        container_name: mysql
        volumes:
            - ./data:/var/lib/mysql
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=123456
        command:
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
            --lower_case_table_names=1
            --max_allowed_packet=128M
            --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
        # volumes:
        #     - mysql-data:/var/lib/mysql
        networks:
            - "net2"
        expose:
            - 80
networks:
    net1:
        driver: bridge
    net2:
        driver: bridge
        